# Generated by Django 5.0.1 on 2024-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_attendance_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to='student_images/'),
            preserve_default=False,
        ),
    ]
